name: KingPlugin
version: 1.0
main: com.example.kingplugin.KingPlugin
api-version: 1.16
commands:
  king:
    description: Show info about the current king.
    usage: /<command>
    permission: kingplugin.command.king
    permission-message: You don't have permission to use this command.
  crown:
    description: Manually crown a new king.
    usage: /crown <player>
    permission: kingplugin.command.crown
    permission-message: You don’t have permission to crown someone.
  resign:
    description: Resign from being king

