name: KingPlugin
version: 1.1
main: com.example.kingplugin.KingPlugin
api-version: 1.13
commands:
  makeking:
    description: Make a player king
    usage: /makeking <player>
  king:
    description: Show current king info
    usage: /king
